# Consola web para administrar dispositivos autorizados SDN AMI.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-device-registry
  namespace: sdn-controller
  labels:
    app: security-device-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-device-registry
  template:
    metadata:
      labels:
        app: security-device-registry
    spec:
      containers:
      - name: registry-web
        image: arturoalvarez/security-device-registry:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: REDIS_SENTINEL_HOST
          value: "redis-sentinel.sdn-controller.svc.cluster.local"
        - name: REDIS_SENTINEL_PORT
          value: "26379"
        - name: REDIS_SENTINEL_MASTER
          value: "mymaster"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: security-device-registry
  namespace: sdn-controller
  labels:
    app: security-device-registry
spec:
  type: LoadBalancer
  ports:
  - name: http-admin
    port: 8082
    targetPort: 5000
    protocol: TCP
  selector:
    app: security-device-registry
